@startuml

scale max 1024 width
scale max 800 height

skinparam defaultTextAlignment center
skinparam componentStyle rectangle
skinparam packageStyle rectangle

skinparam package {
  BorderColor Grey
}

package "Service A (Bounded Context)" #line.dashed {
  component API
  component "Command Handler" as CommandHandler #lightblue
  component "Domain Model" as DomainModel #lightblue
  component "Event Handler" as EventHandler #lightblue
  database "Event\nStore" as EventStore #lightblue
  component Repositories #lightgreen
  database "Read\nDatabase" as ReadDB #lightgreen
}

component "**Service B**\n**(Bounded Context)**" as sB

API -> CommandHandler: Commands
API --> Repositories: Queries
CommandHandler --> DomainModel: Read aggregate;\lAppend new events
EventStore <-up-> DomainModel
EventStore --> EventHandler: Get new events\lin near real-time
EventHandler -up-> ReadDB: Update read model
Repositories --> ReadDB: Execute queries
EventHandler -right-> sB: Integration events\lrepresenting\laggregate state

@enduml
