@startuml

top to bottom direction

hide circle

scale max 1024 width
scale max 800 height

object "**OrderPlacedEvent**" as es1 {
  orderId = 123
  --
  version = 1
  riderId = 234
  route = [...]
  date = 2022-06-20T17:23:12Z
}

object "**Order**" as o1 {
  id = 123
  --
  version = 1
  status = PLACED
  riderId = 234
  route = [...]
  driverId = null
}

object "**OrderAcceptedEvent**" as es2 {
  orderId = 123
  --
  version = 2
  driverId = 345
  date = 2022-06-20T17:27:34Z
}

object "**Order**" as o2 {
  id = 123
  --
  <back:lightgreen>version = 2</back>
  <back:lightgreen>status = ACCEPTED</back>
  riderId = 234
  route = [...]
  <back:lightgreen>driverId = 345</back>
}

object "**OrderCompletedEvent**" as es3 {
  orderId = 123
  --
  version = 3
  date = 2022-06-20T17:49:15Z
}

object "**Order**" as o3 {
  id = 123
  --
  <back:lightgreen>version = 3</back>
  <back:lightgreen>status = COMPLETED</back>
  riderId = 234
  route = [...]
  driverId = 345
}

es3 .down.> o3
es2 .down.> o2
es1 .down.> o1

es1 .> es2
es2 .> es3

o1 -> o2
o2 -> o3

@enduml
