@startuml

scale max 1024 width
scale max 800 height

skinparam packageStyle rectangle

package "Event Store" {
  map "**Account 123**" as a123 {
    v1 => AccountCreated
    v2 => AccountDebited
    v3..v99 => [97 events...]
    v100 => AccountCredited
    v101 => AccountDebited
    v102 => AccountCredited
    v103..v199 => [97 events...]
    v200 => AccountCredited
    v201 => <back:lightgreen>AccountDebited</back>
    v202 => <back:lightgreen>AccountCredited</back>
  }

  map "**Account 123 Snapshots**" as as123 {
    v100 => Snapshot v100
    v200 => <back:lightblue>Snapshot v200</back>
  }
}

map "**Account 123**" as ae123 {
  v200 => <back:lightblue>Snapshot v200</back>
  v201 => <back:lightgreen>AccountDebited</back>
  v202 => <back:lightgreen>AccountCredited</back>
}

object "**Account123 Current State**" as acs123 {
  **id** = 123
  --
  **version** = 202
  **balance** = $1000
}

a123::v100 -> as123::v100
a123::v200 -> as123::v200
as123 -> ae123: Read events
ae123 --> acs123: Restore current state

@enduml
