CREATE TABLE ORDER_AGGREGATE (
  ID UUID PRIMARY KEY,
  VERSION INT4 NOT NULL
);

CREATE TABLE ORDER_EVENT (
  ID BIGSERIAL PRIMARY KEY,
  AGGREGATE_ID UUID NOT NULL REFERENCES ORDER_AGGREGATE (ID),
  VERSION INT4 NOT NULL,
  EVENT_TYPE VARCHAR(255) NOT NULL,
  JSON_DATA JSON NOT NULL,
  UNIQUE (AGGREGATE_ID, VERSION)
);

CREATE TABLE ORDER_EVENT_OUTBOX (
  SUBSCRIPTION_GROUP VARCHAR(255) PRIMARY KEY,
  LAST_ID INT4 NOT NULL
);

CREATE TABLE ORDERS (
  ID UUID PRIMARY KEY,
  ACCEPTED_DATE TIMESTAMP,
  CANCELLED_DATE TIMESTAMP,
  COMPLETED_DATE TIMESTAMP,
  DRIVER_ID UUID,
  PLACED_DATE TIMESTAMP,
  PRICE NUMERIC(19, 2),
  VERSION INT4 NOT NULL,
  RIDER_ID UUID,
  STATUS VARCHAR(255)
);

CREATE TABLE ORDER_ROUTE (
  ORDER_ID UUID NOT NULL REFERENCES ORDERS (ID),
  ADDRESS VARCHAR(255),
  LATITUDE FLOAT8 NOT NULL,
  LONGITUDE FLOAT8 NOT NULL
);

